### PR TITLE
Events unit tests

### PR DESCRIPTION
**Pull request by nicolasmure**
Unit tests for events added in PR #128 :
- Testing the dispatching of pre and post execution events
- Testing the `hasErrors` function of postExecutionEvent
- Testing the `getCommand` and `subRequest` functions of preExecutionEvent

Sorry for not having pushed it earlier, I wasn't very familiar with unit tests :stuck_out_tongue_closed_eyes: 

See you :wink:

### CODE REVIEW

**Comment by nicolasmure** [comment]
Oops, travis CI failed :/
```
PHP Fatal error:  Class 'Symfony\Component\Finder\Finder' not found in /home/travis/build/helios-ag/FMElfinderBundle/vendor/symfony/framework-bundle/Test/KernelTestCase.php on line 116
```
I don't know what it is related about, if someone could explain me that would be great ! :heart_eyes:

**Comment by nicolasmure** [comment]
OK, travis CI is now passing, see commit [240d80d](https://github.com/nicolasmure/FMElfinderBundle/commit/240d80d17ba0254256665bf56d85003d2c0aa985 "webtestcase dependencies") for more informations.
I don't know why StyleCI check is failing...

By the way, I rebased on master :wink:

**Comment by nicolasmure** [comment]
thank you :+1:

**Comment by helios-ag** [comment]
Well done, I will inspect style-ci failures a little bit later.

**Pull request merged**
