### PR TITLE
Multiple upload folder by instance

### PR DESCRIPTION
**Pull request by nicolasmure**
This PR allows to use multiple upload folders by instance setting instead of only one.

This is why I propose it :
I'm making a multiple user application. I use FMElfinderBundle with one instance setting (named `acmeInstance`), where upload path is `/uploads`.
Every users can upload files but I don't want them to see other users' files. So I need to have upload paths like `/uploads/username` where username is the home folder of the current user.
I don't want to create a new instance for each new user so I added an optional route parameter to determine which home folder to use : 
`/elfinder/{instance}/{homeFolder} or /efconnect/{instance}/{homeFolder}`.

For example, accessing to `/elfinder/acmeInstance/bob` route will open elFinder on bob's home folder (located on `/uploads/bob` on local filesystem).

### CODE REVIEW

**Comment by helios-ag** [comment]
Well, PR looks fine, but i don't see how it can be used with elfinder bundle only. May be you will write an integration guide for cors and your usecase? Btw i will accept this PR.

**Comment by nicolasmure** [comment]
Thanks for the merge :+1: 

Here is a little integration guide :

Imagine you're building a multi-users application and you want to use elFinder. You've installed FMElFinderBundle and configured it like this : 

```yaml
# app/config/config.yml
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: simple # other options are tinymce, tinymce4, form, custom and simple, 
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        showhidden: false # defaults to false
                        driver: LocalFileSystem
                        path: /uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
```

So `/uploads` is your root upload path on the local filesystem. If you let it as it, each user will have the same root path when they'll use elFinder, so they will see other user's files.
If you want each user to have its own root path without configuring one instance of FMElFinderBundle by user, you can add a `homeFolder` parameter to the route when accessing to elFinder : `/elfinder/{instance}/{homeFolder} or /efconnect/{instance}/{homeFolder}` :
```javascript
var userName = 'bob'; // grab the username (or id) of the current user
var elFinderInstance = 'default'; // the FMElFinderInstance you wish to use. Even if you're using the default instance, you have to specify it to make the home folder parameter well handled.
var elf = $('#elfinder').elfinder({
    lang: 'en',             // language (OPTIONAL)
    url : 'http://acme.com/efconnect/' + elFinderInstance + '/' + userName,  // connector URL (REQUIRED)
    xhrFields: {
        withCredentials: true
    }
}).elfinder('instance'); 
```
So when Bob user connects to your app and opens up elFinder, he'll see its own (and private) home folder, located on `/uploads/bob` on local filesystem. *Note :* The above example is already integrated in the editor templates proposed by this bundle, you'll have to so if you're using your own custom editor template.

Of course, you have to make sure that home folders exists and are readable and writable. That's why you have to create them when you create a new user in your app.



Should I open a PR for this guide? I hope it is clear enough, it tells what I faced to, and so why I made this PR.
This `homeFolder` parameter only works for `LocalFileSystem` driver, will you be interested by adding it to other [drivers](https://github.com/helios-ag/FMElfinderBundle/blob/master/Configuration/ElFinderConfigurationReader.php#L101)?

**Comment by helios-ag** [comment]
I'm currently working on implementing flysystem support, btw i don't how many people use other drivers than LocalFileSystem, but i suppose 99% users working with it.

**Comment by nicolasmure** [comment]
OK, I let it as it so.
I'm gonna PR for explication guides.

Thx :wink:

**Pull request merged**
