### PR TITLE
Fixes #497 mainUrl didn't contain asset path

### LINKED ISSUE #497: The assets for elfinder.min.js are giving 404 when using a different asset_path
**Describe the bug**
I have my `asset_path` configured to a different folder now with the recent changes: https://github.com/helios-ag/FMElfinderBundle/pull/493 i breaks it probably was already broke before this fix. Some more context: https://github.com/helios-ag/FMElfinderBundle/pull/493/files#r1162540304

**To Reproduce**
Have a `asset_path` defined to different folder then the default and check you get 404 when loading the assets.

### PR DESCRIPTION
**Pull request by JohJohan**
Add missing asset path for main_url to correctly load the assets.

Fixes #497

### CODE REVIEW

**Comment by JohJohan** [comment]
@helios-ag and @UlrichHP  when you have time can you check it?

**Comment by JohJohan** [comment]
> Hi @JohJohan,
> I tried your solution but it is not working for me.
> 
> In my case the assets_path is not defined because the bundles folder is located directly in the public directory.
> 
> Your solution seems to make it mandatory to have the bundles folder in another folder.

Okay i can look into that thanks for the feedback. Maybe checking if the 'asset_path' is set might be enough to fix it. I will have a look.

**Comment by JohJohan** [comment]
I see default value for 'asset_path' is 'assets'. If i understand you correctly you set it to 'null' value?

**Comment by UlrichHP** [comment]
> I see default value for 'asset_path' is 'assets'. If i understand you correctly you set it to 'null' value?

I didn't have to. I left it commented like in the [README - Basic configuration](https://github.com/helios-ag/FMElfinderBundle#basic-configuration)

I think the assets_path option never really worked...
Even in the controller, it seems it is only used to define a prefix param which is not used afterwards.

**Comment by JohJohan** [comment]
> > I see default value for 'asset_path' is 'assets'. If i understand you correctly you set it to 'null' value?
> 
> I didn't have to. I left it commented like in the [README - Basic configuration](https://github.com/helios-ag/FMElfinderBundle#basic-configuration)
> 
> I think the assets_path option never really worked... Even in the controller, it seems it is only used to define a prefix param which is not used afterwards.

@helios-ag can you confirm the `I think the assets_path option never really worked`? Otherwise we have a option now that we dont support and we should probably remove it.

But i need it because in a project i have my bundle assets in a different folder there not in `/assets` there in `/public/cdn/`. So using the `asset_path` is good to fix that, but actually using the `asset_path` it will break others that use default like @UlrichHP 

What i can do is:
```diff
-   $mainUrl = $package->getUrl('/bundles/fmelfinder/js');
+  $path = '/bundles/fmelfinder/js';
+  if ($this->params['assets_path'] !== 'assets') {
+    $path = '/'.$this->params['assets_path'].$path;
+  }
+  $mainUrl = $package->getUrl($path);
```

So that it wont break it @helios-ag what do you think? Right now like i said it wont work for my project and i pin it to `12.2.1`

**Comment by UlrichHP** [comment]
@JohJohan 
This solution works for me too :smile: 
Maybe you can modify the if loop condition to this :  `$this->params['assets_path'] !== '/' && $this->params['assets_path'] !== 'assets'` since in the README, it is the default value ?

**Comment by JohJohan** [comment]
> @JohJohan This solution works for me too smile Maybe you can modify the if loop condition to this : `$this->params['assets_path'] !== '/' && $this->params['assets_path'] !== 'assets'` since in the README, it is the default value ?

Yeah that is possible but it feels wrong to skip the config parameter, but using it for the default will break it @helios-ag i'm curious what you think about it?

**Comment by helios-ag** [comment]
@johanadivare seems like prefix not used anymore, in this case prefix can be also eliminated from controller too

**Comment by JohJohan** [comment]
> @johanadivare seems like prefix not used anymore, in this case prefix can be also eliminated from controller too

Okay yes, but how should i fix loading my assets then? Now with the current code it loads `https://x.net/bundles/fmelfinder/js/elfinder.min.js` (404) while it should be loading `https://x.net/cdn/bundles/fmelfinder/js/elfinder.min.js` (200) as i have everything in a `cdn` folder in my `public` folder

**Comment by Smanst3r** [comment]
`sprintf('/%s/bundles/fmelfinder/js', $this->params['assets_path'])`
if I set `assets_path: ''` the result will be **//bundles/fmelfinder/js**

Is there a reason why it cannot be done without the leading slash?
`sprintf('%s/bundles/fmelfinder/js', $this->params['assets_path'])` 
```
e.g.
assets_path: /path-to-somethere/where-you-want # /path-to-somethere/where-you-want/bundles/fmelfinder/js
assets_path: '' # /fmelfinder/js
```
And one more:
the command elfinder:install option --docroot=public_html should be equal to --docroot=<assets_path> according to this PR? 

Thanks for clarifying

**Pull request merged**
