### PR TITLE
Allow setting the directoryPerm parameter

### PR DESCRIPTION
**Pull request by danut007ro**
Allow setting the directoryPerm parameter. Related to https://github.com/thephpleague/flysystem/pull/457 and https://github.com/thephpleague/flysystem-sftp/pull/6

### CODE REVIEW

**Comment by helios-ag** [comment]
Can you rebase your PR?

**Comment by danut007ro** [comment]
Done

**Comment by helios-ag** [comment]
Thank you!

**Comment by helios-ag** [comment]
Tagged as 5.0.3

**Pull request merged**
