### PR TITLE
Respect custom loader

### PR DESCRIPTION
**Pull request by zorn-v**
Fixes https://github.com/helios-ag/FMElfinderBundle/issues/480

### CODE REVIEW

**Comment by helios-ag** [comment]
Seems fine, thanks!

**Comment by helios-ag** [comment]
I want to make some changes, and also because it changes signature of public methods, its needs major version bump.

**Comment by helios-ag** [comment]
Otherwise its needs a bit rework, probably by setting loader via set method (like `setLoader($loader)`), without changing  `load` method signature

**Comment by zorn-v** [comment]
I see, will wait then.

**Pull request merged**
