### PR TITLE
connector options override

### PR DESCRIPTION
**Pull request by nicolasmure**
Hi,

This is a PR to allow connector's options override. Here is the full list of available options : https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options

Previously defined options in app/config/config.yml file are not overriden by this setting, only new ones (who weren't configurable before) are given to the connector.

See you :smile:

### CODE REVIEW

**Comment by helios-ag** [comment]
Well i think its better to enumerate all options in configuration, there is not much left to include.

**Comment by nicolasmure** [comment]
ok options are now enumerated.

To use them in config.yml, convert their names from camelCased to under_scored.

**Comment by helios-ag** [comment]
Well done @nicolasmure :+1:

**Comment by nicolasmure** [comment]
hey thanks :smiley: !

**Pull request merged**
